[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read", path = "test/data"}]
solc_version = "0.8.21"

# TODO turn off the memory limit
memory_limit = 8446744073709551615
