name: test

on:
  push:
    branches:
      - main
  pull_request:

env:
  FOUNDRY_PROFILE: ci
  # this is a bit fragile, but probably most convenient for now. move to a tag soon.
  FOUNDRY_BRANCH: sunscreen

jobs:
  test:
    strategy:
      fail-fast: true

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Clone Foundry
        uses: actions/checkout@v3
        with:
          repository: Sunscreen-tech/foundry
          ref: ${{ env.FOUNDRY_BRANCH }}
          path: foundry

      - name: Get Foundry commit hash
        id: foundry-hash
        working-directory: foundry
        run: |
          echo "hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Restore forge binary if cached
        uses: actions/cache/restore@v3
        id: cache
        with:
          path: ~/.cargo/bin/forge
          key: ${{ runner.os }}-${{ steps.foundry-hash.outputs.hash }}-forge

      - name: Install Foundry
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: foundry
        run: cargo install --path cli --profile local --bins --locked --force

      - name: Save new forge binary
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: ~/.cargo/bin/forge
          key: ${{ runner.os }}-${{ steps.foundry-hash.outputs.hash }}-forge

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
